package ADMIN;

import config.DataBaseCon;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class userProfile extends javax.swing.JFrame {

    /**
     * Creates new form userPro
     */
    public userProfile(String email) {
    initComponents();
    
    System.out.println("Opening profile for: " + email);
    
    if (email == null || email.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Invalid user session");
            dispose();
            return;
        }

        loadUserProfile(email);
    }

    // ================= LOAD USER DATA + IMAGE =================
    private void loadUserProfile(String email) {
        String sql =
        "SELECT first_name, last_name, email, type, status, idpicture " +
        "FROM tbl_users " +
        "WHERE LOWER(TRIM(email)) = LOWER(TRIM(?))";

    try (Connection con = DataBaseCon.connectDB();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setString(1, email);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {

            txtFirstname.setText(rs.getString("first_name"));
            txtLastname.setText(rs.getString("last_name"));
            txtEmail.setText(rs.getString("email"));
            txtUsertype.setText(rs.getString("type"));
            txtStatus.setText(rs.getString("status"));

            byte[] imgBytes = rs.getBytes("idpicture");
            if (imgBytes != null && imgBytes.length > 0) {
                ImageIcon icon = new ImageIcon(imgBytes);
                Image img = icon.getImage().getScaledInstance(
                        lbl_photo.getWidth(),
                        lbl_photo.getHeight(),
                        Image.SCALE_SMOOTH
                );
                lbl_photo.setIcon(new ImageIcon(img));
            } else {
                lbl_photo.setIcon(null);
            }

        } else {
            JOptionPane.showMessageDialog(this, "User not found!");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading profile: " + e.getMessage());
    }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtEmail = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        txtUsertype = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbl_photo = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("USERS PROFILE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 289, 100, 30));

        txtEmail.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 61, 250, 20));

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Email:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 63, -1, -1));

        txtFirstname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtFirstname.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(txtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 99, 250, 20));

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("First Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 101, -1, -1));

        txtLastname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtLastname.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(txtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 147, 250, 21));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 225, 0));
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 147, -1, 21));

        jLabel7.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("User Type:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 186, -1, 30));

        txtStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtStatus.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(txtStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 230, 20));

        txtUsertype.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtUsertype.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.add(txtUsertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 250, 20));

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Status:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 234, 50, 30));

        lbl_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0), 2));
        lbl_photo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_photo.setPreferredSize(new java.awt.Dimension(150, 150));
        jPanel2.add(lbl_photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 150, 150));

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Upload");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 360));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/USER.PNG"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 370, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      String email = txtEmail.getText();
    String fname = txtFirstname.getText();
    String lname = txtLastname.getText();

   
    String sql = "UPDATE tbl_users SET first_name = ?, last_name = ? WHERE email = ?";

    
    DataBaseCon conf = new DataBaseCon();
    
    try {
        
        conf.addRecord(sql, fname, lname, email);
        
        JOptionPane.showMessageDialog(this, "Saved Successfully!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Save Error: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser chooser = new JFileChooser();
    chooser.setDialogTitle("Select Image");
    chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

    if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();

        try {
            BufferedImage bi = ImageIO.read(file);

            if (bi == null) {
                JOptionPane.showMessageDialog(this, "Invalid image file!");
                return;
            }

            // Show image
            Image img = bi.getScaledInstance(150, 150, Image.SCALE_SMOOTH);
            lbl_photo.setIcon(new ImageIcon(img));

            // Convert to byte[]
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bi, "png", baos);
            byte[] imageBytes = baos.toByteArray();

            // DEBUG
            System.out.println("Image bytes length: " + imageBytes.length);
            System.out.println("Saving for email: " + txtEmail.getText());

            // SAVE TO DB
            Connection conn = DataBaseCon.connectDB();
            String sql = "UPDATE tbl_users SET idpicture = ? WHERE email = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setBytes(1, imageBytes);
            pst.setString(2, txtEmail.getText().trim());

            int updated = pst.executeUpdate();

            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "Image saved to database!");
            } else {
                JOptionPane.showMessageDialog(this,
                    "NO ROW UPDATED ❌\nCheck email match.");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
    java.awt.EventQueue.invokeLater(() -> {
        new userProfile("user1").setVisible(true); // must EXIST in tbl_users
    });
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtFirstname;
    private javax.swing.JLabel txtLastname;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtUsertype;
    // End of variables declaration//GEN-END:variables
}
